name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - '1'
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -fsSL https://install.julialang.org | sh -s -- -y
          source /home/runner/.bashrc
          source /home/runner/.profile
          source /home/runner/.bash_profile
          juliaup config channelsymlinks true
          juliaup add 1.6
          juliaup add 1.7
          juliaup add 1.8
          juliaup add 1.9
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
